apiVersion: apps/v1
kind: Deployment
metadata:
  name: appconfig-mobile-recharge
  labels:
    appconfig: mobile-recharge
spec:
  replicas: 1
  selector:
    matchLabels:
      appconfig: mobile-recharge
  template:
    metadata:
      labels:
        appconfig: mobile-recharge
    spec:
      containers:
      - name: appconfig-mobile-recharge
        image: geetmanghnani/appconfig-mobile-recharge:0.0.3
        ports:
          - containerPort: 3000
            protocol: TCP
        env:
          - name: MOBILE_RECHARGE
            value: "true"
